branch-defaults:
  default:
    environment: lucy-server-dev
global:
  application_name: lucy-server
  default_ec2_keyname: Anant-key-pair
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
