branch-defaults:
  master:
    environment: lucy-server-env
global:
  application_name: scaleMed-android
  default_ec2_keyname: Anant-key-pair
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
